apiVersion: v1
kind: Service
metadata:
   labels:
      app: webapp
   name: webapp-service
spec:
   type: NodePort
   selector:
       name: simple-webapp
   ports:
     - port: 8080
       targetPort: 8080
       nodePort: 30080
