apiVersion: v1
kind: Pod
metadata:
  name: webpod 
  labels:
     env: prod
     app: frontend 
spec:
  containers:
  - name: webapp
    image: nginx 
    ports:
    - containerPort: 8080
  restartPolicy: OnFailure 
  tolerations:
  - key: "app"
    operator: "Equal"
    value: webapp 
    effect: Noschedule 
  
